### ISSUE TITLE
Reference mis-match causes java.lang.NoSuchMethodException in report form activity

### ISSUE THREAD

**Issue by brendandm** [WaterReporter/WaterReporter-Android#15]
Stack trace:

```
java.lang.IllegalStateException: Could not find a method showDatePickerDialog(View) in the activity class android.support.v7.internal.widget.TintContextWrapper for onClick handler on view class android.support.v7.widget.AppCompatEditText with id 'date'
    at android.view.View$1.onClick(View.java:4285)
    at android.view.View.performClick(View.java:5254)
    at android.view.View$PerformClick.run(View.java:21179)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NoSuchMethodException: showDatePickerDialog [class android.view.View]
    at java.lang.Class.getMethod(Class.java:665)
    at android.view.View$1.onClick(View.java:4278)
    ... 10 more
```

**Comment by brendandm** [comment]
This had to do with an incorrect method reference related to the report date field (date picker). Corrected in v1.4.1.
